### ISSUE TITLE
不能打出jar包AndroidStudio2.3.3 , gradle3.3, 在mac 10.11.6环境下

### ISSUE THREAD

**Issue by alordred** [adisonhuang/buildJar#4]
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/lihongsheng/Desktop/打jar包/TestJarPlugin-master/app/build.gradle' line: 45

* What went wrong:
A problem occurred evaluating project ':app'.
> Could not set unknown property 'includeClass' for object of type com.adison.gradle.plugin.BuildJarExtension.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by alordred** [comment]
补充下，在mac 10.11.6环境下

**Comment by alordred** [comment]
buildscript {
    repositories {
        mavenCentral()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.jfrog.bintray.gradle:gradle-bintray-plugin:1.7'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.4.1'
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath 'com.adison.gradleplugin:jar:1.0.1'
    }
}

allprojects {
    repositories {
        mavenCentral()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

apply plugin: 'jar-gradle-plugin'
BuildJar{
    //输出目录
    outputFileDir= project.buildDir.path+"/jar"
    //输出原始jar包名
    outputFileName="test.jar"
    //输出混淆jar包名
    outputProguardFileName="test_proguard.jar"
    //混淆配置
    proguardConfigFile="proguard-rules.pro"
    //是否需要默认的混淆配置proguard-android.txt
    needDefaultProguard=true
    applyMappingFile="originMapping/mapping.txt"
    //需要输出jar的包名列表,当includePackage&includeClass为空时，则默认全项目输出,支持多包,如 includePackage=['com/adison/testjarplugin/include','com/adison/testjarplugin/include1'...]
    includePackage=['com/adison/testjarplugin/include']
    //需要输出jar的类名列表
    includeClass=['com/adison/testjarplugin/include/TestInclude.class']
    //不需要输出jar的jar包列表,如['baidu.jar','baidu1.jar'...]
    excludeJar=[]
    //不需要输出jar的类名列表,如['baidu.calss','baidu1.class'...]
    excludeClass=['com/adison/testjarplugin/TestExcude.class']
    //不需要输出jar的包名列表,如 excludePackage=['com/adison/testjarplugin/exclude','com/adison/testjarplugin/exclude1'...]
    excludePackage=['com/adison/testjarplugin/exclude']
}

Error:(29, 0) Could not find method BuildJar() for arguments [build_ecxg4du1vq3z87n8br1ejjeaa$_run_closure3@34934271] on root project 'buildJar-master' of type org.gradle.api.Project.
<a href="openFile:/Users/lihongsheng/Desktop/buildJar-master/build.gradle">Open File</a>

**Comment by alordred** [comment]
Error:(126, 0) Plugin with id 'jar-gradle-plugin' not found.
<a href="openFile:/Users/lihongsheng/Desktop/buildJar-master/BuildJarPlugin/build.gradle">Open File</a>

**Comment by alordred** [comment]
Error:(127, 0) Could not find method BuildJar() for arguments [build_doayeou06y4y9c6zezhlzg8q9$_run_closure10@1edb5d86] on project ':BuildJarPlugin' of type org.gradle.api.Project.
<a href="openFile:/Users/lihongsheng/Desktop/buildJar-master/BuildJarPlugin/build.gradle">Open File</a>

**Comment by adisonhyh** [comment]
使用1.0.3试试
