### ISSUE TITLE
Android 2.3.3  Gradle 2.3.3 Error 不支持在Library中打包

### ISSUE THREAD

**Issue by xiayouli0122** [adisonhuang/buildJar#5]
在Library中使用
Error:(34, 0) Could not find method BuildJar() for arguments [build_bttibwd2op6piuzbul4p8diot$_run_closure3@254b60cc] on project ':core' of type org.gradle.api.Project.
<a href="openFile:**\core\build.gradle">Open File</a>

在App中使用可以执行

**Comment by Nevall** [comment]
代码里面限制了仅在AppPlugin里面使用 
   @Override
    public void apply(Project project) {
        DefaultDomainObjectSet<ApplicationVariant> variants
        if (project.getPlugins().hasPlugin(AppPlugin)) {
            variants = project.android.applicationVariants;

            project.extensions.create(EXTENSION_NAME, BuildJarExtension);

            applyTask(project, variants);
        }
    }

**Comment by Nevall** [comment]
@xiayouli0122 
代码里面限制了仅在AppPlugin里面使用
@override
public void apply(Project project) {
DefaultDomainObjectSet variants
if (project.getPlugins().hasPlugin(AppPlugin)) {
variants = project.android.applicationVariants;

        project.extensions.create(EXTENSION_NAME, BuildJarExtension);

        applyTask(project, variants);
    }
}

**Comment by adisonhyh** [comment]
使用1.0.3 试试
