### ISSUE TITLE
demo 编译出错 附log

### ISSUE THREAD

**Issue by yubang322311** [adisonhuang/buildJar#6]
FAILURE: Build failed with an exception.

* What went wrong:
Task 'buildJar' not found in root project 'TestJarPlugin'. Some candidates are: 'build'.

* Try:
Run gradlew tasks to get a list of available tasks. Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by adisonhyh** [comment]
加上 --stacktrace 看看详细错误
