### ISSUE TITLE
jar 在ecplise 上导致gc 无响应闪退

### ISSUE THREAD

**Issue by JsonYuu** [adisonhuang/buildJar#7]
用AS 把application 打成jar  ，使用您的gradle 插件，在ecplise 使用打的jar ，容易造成ecplise  无响应，gc闪退。ecplise 都已经配置过ini 文件 改过内存大小了。实在不清楚原因。
请问您下，这可能什么导致的呢？
谢谢了...

**Comment by adisonhyh** [comment]
把 log 贴出来看看
